[package]
name = "gltut-wgpu"
version = "0.1.0"
authors = ["Charles Ellis <hamled@hamled.dev>"]
edition = "2021"

[dependencies]
winit = { version = "0.25", default-features = false, features = ["wayland"] }
wgpu = "0.11"
pollster = "0.2"
cgmath = "0.18"
